apiVersion: apps/v1
kind: Deployment
metadata:
    name: gitui-deployment
    labels:
        app: gitui
        type: frontend
spec:
    template:
        metadata:
            name: gitui-pod
            labels:
                app: gitui
                type: frontend
        spec:
            containers:
            - name: gitui-container
              image: 792429589635.dkr.ecr.ap-south-1.amazonaws.com/gitfocus
              ports:
              - containerPort: 4200  
    replicas: 3
    selector: 
        matchLabels:
            type: frontend
---
apiVersion: v1
kind: Service
metadata:
    name: gitui-lb
spec:
    type: LoadBalancer
    ports:
        - targetPort: 4200
          port: 4200
    selector: 
        app: gitui